### ISSUE TITLE
Add ErrorActionPreference to win_shell

### ISSUE THREAD

**Issue by davetapley** [ansible-collections/ansible.windows#122]
##### SUMMARY

When running mutli-line Powershelll scripts with [`ansible.windows.win_shell`](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_shell_module.html),
**any failure not occurring on the last line** will:

1. Be silently ignored.
1. Set return value `rc` to `0` (indicating success, per the docs).
1. Hide errors in `stderr` return value.

This happens because the [`ErrorActionPreference`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7#erroractionpreference) preference variable is set to `Continue`, by default.

This is unlikely to be desired behavior when running via Ansible (where output is not visible),
so I propose we:

1. Allow `ErrorActionPreference` to be set via a parameter, and optionally:
1. Make a breaking change to override the default with `Stop`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Module `ansible.windows.win_shell`.

Proposed new parameter `error_action_preference` [having 8 options given here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7#erroractionpreference). Default to either `Continue` or `Stop`.
This new parameter would only be valid when using PowerShell as the executable, which there is precedence for in the [`no_profile`](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_shell_module.html#parameter-no_profile) parameter.

##### ADDITIONAL INFORMATION

E.g. for the [example given here](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_shell_module.html#examples):

```yaml
- name: Run multi-lined shell commands
  ansible.windows.win_shell: |
    $value = Test-Path -Path C:\temp
    if ($value) {
        Remove-Item -Path C:\temp -Force
    }
    New-Item -Path C:\temp -ItemType Directory

```

If the first line were to contain a typo,
the `win_shell` task would still complete 'successfully',
even though the behavior of the task would be undefined.

---

Note I recreated this here from https://github.com/ansible/ansible/issues/72478

**Comment by davetapley** [comment]
If this were implemented then the most contentious decision would be whether `ErrorActionPreference` defaults to `Continue` (existing behavior) or `Stop` (new behavior).:

|          | Pros                                                                                                                                      | Cons                                                                                            |
|----------|-------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------|
| `Continue` |  Keeps existing functionality. Wouldn't cause exiting tasks to start failing.                                                                                                             | Newly written tasks may fail silently if user doesn't notice `ErrorActionPreference` parameter and/or warning in docs.            |
| `Stop`     | All existing and future tasks would fail unless user explicitly sets `Continue` to indicate they understand what's going on. | Existing tasks which are currently failing silently will require fixing or explicit `Continue` to be set. |

Please react 👍🏻 if you are in favor of making the breaking change to default to `Stop`, or 👎🏻 to retain existing `Continue` behavior.

**Comment by mwtrigg** [comment]
Won't adding "-ErrorAction:Stop" to the shell command produce the same result?  I'm pretty sure that's how I achieved it when last I. Ended the functionality.

**Comment by mwtrigg** [comment]
> If the first line were to contain a typo,
the win_shell task would still complete 'successfully',
even though the behavior of the task would be undefined.

This is how it would work with an interactive PowerShell session as well, because the failed `Remove-Item` does not produce a terminating error.  I would prefer that anything I use on a `win_shell` behave just as it does on the interactive shell.

**Comment by davetapley** [comment]
Interesting, thanks @mwtrigg, I wonder what could cause a difference? 🤔 

I'll see if I can get a [test](https://github.com/ansible-collections/ansible.windows/blob/main/tests/integration/targets/win_shell/tasks/main.yml) to repro it and report back.

**Comment by davetapley** [comment]
I just ran in to this again 'organically'.

For context, I'm replicating [this guide on setting up FTP with IIS with Powershell](https://4sysops.com/archives/install-and-configure-an-ftp-server-with-powershell/).

I just copied this chunk over and missed adding `ErrorActionPreference  = "Stop"`.

```yaml
    - name: Set SSL policy to allow
      ansible.windows.win_shell: |
        $ErrorActionPreference = "Stop"
        $FTPSiteName = 'FTP Site'
        $FTPSitePath = "IIS:\Sites\$FTPSiteName"
        $SSLPolicy = @(
            'ftpServer.security.ssl.controlChannelPolicy',
            'ftpServer.security.ssl.dataChannelPolicy'
        )
        Set-ItemProperty -Path $FTPSitePath -Name $SSLPolicy[0] -Value $false
        Set-ItemProperty -Path $FTPSitePath -Name $SSLPolicy[1] -Value $false
        echo $null >> C:\ftp\.ansible_state\ssl_allow
      args:
        creates: C:\ftp\.ansible_state\ssl_allow
```

As before the task completed successfully, but didn't appear to work.

After adding `ErrorActionPreference  = "Stop"` and re-running, it failed with:

```
TASK [Set SSL policy to allow] ***************************************************************************************************
fatal: [ftp_test]: FAILED! => {"changed": true, "cmd": "$ErrorActionPreference = \"Stop\"\n$FTPSiteName = 'FTP Site'\n$FTPSitePath = \"IIS:\\Sites\\$FTPSiteName\"\n$SSLPolicy = @(\n    'ftpServer.security.ssl.controlChannelPolicy',\n    'ftpServer.security.ssl.dataChannelPolicy'\n)\nSet-ItemProperty -Path $FTPSitePath -Name $SSLPolicy[0] -Value $false\nSet-ItemProperty -Path $FTPSitePath -Name $SSLPolicy[1] -Value $false\necho $null >> C:\\ftp\\.ansible_state\\ssl_allow", "delta": "0:00:00.421776", "end": "2020-11-06 06:50:57.992607", "msg": "non-zero return code", "rc": 1, "start": "2020-11-06 06:50:57.570830", "stderr": "Set-ItemProperty : Cannot find drive. A drive with the name 'IIS' does not exist.\r\nAt line:8 char:1\r\n+ Set-ItemProperty -Path $FTPSitePath -Name $SSLPolicy[0] -Value $false\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (IIS:String) [Set-ItemProperty], DriveNotFoundException\r\n    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand", "stderr_lines": ["Set-ItemProperty : Cannot find drive. A drive with the name 'IIS' does not exist.", "At line:8 char:1", "+ Set-ItemProperty -Path $FTPSitePath -Name $SSLPolicy[0] -Value $false", "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : ObjectNotFound: (IIS:String) [Set-ItemProperty], DriveNotFoundException", "    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand"], "stdout": "", "stdout_lines": []}
```

In this case because I missed copying `Import-Module WebAdministration` over.

---

What peculiar is how close this is to @mwtrigg 's snippet. Comparing `stderr`s:

Mine: ` "Set-ItemProperty : Cannot find drive`
@mwtrigg: `"Remove-Item : Cannot find path.`

🤔

**Comment by jborean93** [comment]
> Allow ErrorActionPreference to be set via a parameter, and optionally:

I would be a -1 on this. The `win_shell` module is designed to be shell agnostic. The default is `powershell` but adding in a parameter that is only useful for 1 shell isn't really ideal. There's also a question as to how do we handle `pwsh.exe` that someone might set on their executable. What if someone has `pwsh7.exe` or `pwsh8.exe` to handle multiple PowerShell versions. Should we apply the EAP to anything matching those patterns or not?

The simplest solution if you want EAP to be Stop is to have that in your shell script that you are running. There's very little difference between

```yaml
- win_shell: |
    $ErrorActionPreference = 'Stop'
    ...
```

and

```yaml
- win_shell: |
    ...
  args:
    error_action_preference: Stop
```

If anything the latter is more verbose and as I mentioned before it's only specific to the PowerShell shell type.

I'm also quite reluctant to add more injections to the code a user has specified but there is [a precedence](https://github.com/ansible-collections/ansible.windows/blob/28ce8268ca0a0fbc6ebfed456efd242ff4799aa3/plugins/modules/win_shell.ps1#L73) for that already so that isn't a strong argument against.

> Make a breaking change to override the default with Stop.

Putting aside the problems I mentioned above with handling the injection of this code and what shells to actually apply it to. Changing the default behaviour here is very likely to not happen. People with existing tasks will be implicitly relying on the current behaviour of `Continue` whether they realise it or not. This module will be one of the more common ones used for Windows and thus the impact of a breaking change will be quite dramatic.

While I agree that it is saner to have the default action here be `Stop`, the practical limits and stability contract we have with the current `win_shell` module will stop us from making this change. What I see as a more practical solution is to have a `win_powershell` module that uses the .NET API to run PowerShell scripts outside of an actual PowerShell process. The reason why this hasn't been done yet is due to a few reasons

* You cannot dynamically set the `pwsh` interpreter to use. It uses the currently running engine which in this case is always `powershell.exe`
* The logic for determining whether an error has occurred can be tricky, you can see how complex the current logic is for when we run modules https://github.com/ansible/ansible/blob/0fa1cd88ce57167292803e9257fe2ed50cb3e1e0/lib/ansible/executor/powershell/module_wrapper.ps1#L123-L221
* Dealing with console/stdout output is tricky so things like `Write-Host` may not act like people expect

In saying that we could gain a few benefits from this approach like

* Pass in complex objects like lists/dicts from Ansible as an actual object to the script
* Automatically converting output objects to JSON and returning that as the module output for direct parsing in Ansible
* Set the EAP to Stop by default and have it controlled by the user if desired
* Output each stream as a separate object that can be parsed in the playbook
* Set timeouts on runnning the command

I'll add this discussion Windows Working Group [agenda](https://github.com/ansible/community/issues/517) to see if we want to investigate the EAP more as a group but my feeling is this is not something we can change.

**Comment by briantist** [comment]
I agree with not changing the behavior for all the reasons jborean93 mentioned.

Also this deserves a callout:
> Another problem, not really with Stop is the behaviour of error records and terminating errors in PowerShell. The latter will stop the pipeline and should return a non-zero RC while the former has the behaviour you currently describe. This is just the nature of PowerShell and while it is can be difficult to understand when you get started, the power or error records are quite important when you deal with pipelining objects.

PowerShell itself defaults to `Continue` and I think that's what people should expect when running PowerShell via `win_shell` as well. 

If you were writing a script to be run in `powershell.exe` you'd have to set `$ErrorActionPreference` in your script if you wanted something other than the default, so I think it's reasonable to expect you'd have to do the same here (which is also the workaround recommended above).
