### ISSUE TITLE
[RFE] Allow CredSSP to restrict authentication methods

### ISSUE THREAD

**Issue by mdinwoodie** [ansible-collections/ansible.windows#141]
##### SUMMARY
Currently, when using WinRM with CredSSP it will attempt to use Kerberos/NTLM in order until it successfully connects. This RFE is to add the ability to restrict CredSSP to connect only by one method, failing if it can't connect.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
winrm.py

**Comment by jborean93** [comment]
This is not something that can be enabled in Ansible. You will need to add a kwarg to the [Protocol class in pywinrm](https://github.com/diyan/pywinrm/blob/667703f3ddebc67cab72d86620315c739bfd7262/winrm/protocol.py#L31-L44) that accepts the CredSSP auth selection. Once that is added you can reference any of those kwargs by setting `ansible_winrm_<kwarg>` as an Ansible var and Ansible will automatically pass it through.

Luckily for you, the psrp connection plugin already exposes this so you can use [credssp_auth_mechanism](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/psrp_connection.html#parameter-credssp_auth_mechanism) by setting `ansible_psrp_credssp_auth_mechanism: kerberos` in your vars. The underlying library that `psrp` uses exposes this option which is why you can use it today.

For Ansible there's nothing we can do here, the underlying functionality is called in pywinrm and pywinrm must expose this as a configurable feature.
