### ISSUE TITLE
Check Mode for win_package is not working correctly.

### ISSUE THREAD

**Issue by JonathanG3** [ansible-collections/ansible.windows#208]
##### SUMMARY

**Check Mode** for win_package module is not working correctly.
Fails on 'The file at the local path c:\\path\\to\\file\\PackageName cannot be reached'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.windows.win_package

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
(Nothing came out)
```

##### OS / ENVIRONMENT

Target servers - Windows Server 2016 Standard
We are using AWX deployed on Kubernetes and running playbooks via ansible-runner (this is where the output above is from) by using Container Groups.

##### STEPS TO REPRODUCE

1. Use win_package module in your playbook.
2. Provide path and other needed information.
3. Run in Chehck mode.

```yaml
- name: Install package agent
  win_package:
    path: "c:\\temp\\Package"
    arguments: "/q"
    product_id: "<PRODUCT_ID>"
```

##### EXPECTED RESULTS

Report changes (like "Will install Package") without actually installing the package

##### ACTUAL RESULTS

Fails on the fact the the package doesn't exist on the path I provided.

```paste below
{
  "reboot_required": false,
  "changed": false,
  "msg": "the file at the local path c:\\temp\\Package cannot be reached",
  "_ansible_no_log": false
}
```
##### NOTES
I didn't know where to write it so I added a section - 
I also tried adding "check_mode: yes" to try see if it help but since the module supports check_mode it still try to run with it's check mode enabled.

**Comment by jborean93** [comment]
If it's failing because the path doesn't exist then that's what would have happened when you are in normal mode. There's nothing special about the path you've specified (it's local) so if it's saying it doesn't exist then it doesn't exist.

**Comment by JonathanG3** [comment]
The issue is that I am running in Check mode in the AWX job template, so I shouldn't be running in Normal mode:
![image](https://user-images.githubusercontent.com/80903896/115677434-24380500-a359-11eb-83a1-e9b0ec79c570.png)

**Comment by jborean93** [comment]
I’m not sure why it’s an issue, there is no difference here between check and normal mode. It’s going to fail in both of the path does not exist.

**Comment by JonathanG3** [comment]
From what you say, I understand that this intentional? why is there a need for the .exe/.msi file when I'm running in check mode? My use case was to use the win_package module is to install when running normally and telling me if there a need to run when running in check mode.
I thought that by providing the product ID I could check get the report if there is a need to install, but it seems that a path is required even when running in check mode.

**Comment by jborean93** [comment]
It is somewhat intentional, the trouble with check mode IMO is that the standards as to what should constitute a failure and how strict it should be is not really set in stone. Some module check mode functionality acts like you have mentioned while others (like `win_package`) take a more literal if it won't work when running normally then it should fail in the same way. In this case if you were to run `win_package` without the path specified being accessible then `win_package` would fail in normal mode hence why it also does so in check mode.

> I thought that by providing the product ID I could check get the report if there is a need to install, but it seems that a path is required even when running in check mode.

The path is required when `state: present`. It may technically not be required if the package is already installed but now you have a module that has a required pre-state to function correctly.

Typically what I have done in the past is add `ignore_errors: '{{ ansible_check_mode }}'` to my tasks that act like this. This allows it to run and tell you whether a change is required if the path exists in check mode and not fail if it's not in check mode. It's not perfect but it will stop your playbook from failing.

I'll bring this up for discussion at the next Windows Working Group meeting https://github.com/ansible/community/issues/581. You are more than welcome to join and discuss it with us.

**Comment by jborean93** [comment]
This issue was discussed in the Windows Working Group and it was decided that the current behaviour is the desired behaviour. Essentially a module should behave the same way in check mode as it would normally. In this case when `state: present` is set then it expects the path to be defined and exist in case it needs to be installed. The path check could potentially happen after but that complicates things further as it could be required to get the `product_id` to check if it's installed and also adds an error condition that may or may not fire depending on the existing state + whether it's installed or not.

Ultimately it is the responsibility of the playbook to work in check more or not. That could mean you set `ignore_errors: '{{ ansible_check_mode }}'` on the task to ignore errors when run in check mode or do stuff like @briantist has mentioned to set up the pre-requisites in check mode even if it does actually make a change.

Unfortunately nothing is going to solve all scenarios, we even had 2 people in the meeting with different views of how to use check mode. Because of that we decided that having this hard line in the sand that states check mode will behave in the exact same way as normal mode made things clearer and easier for people to understand.
