### ISSUE TITLE
win_dns_client.ps1 always set DNS on NICs

### ISSUE THREAD

**Issue by allanmo79** [ansible-collections/ansible.windows#211]
##### SUMMARY
ansible.windows.win_dns_client, always return changed=$true, when looking in win_dns_client.ps1 it loops through a Hashtable "$AddressFamilies" (func Get-RegistryNameServerInfo) that dosnt exist, thus it never sets RegInfo in custom object. As a result it will always set DNS on nics! and return changed eq $true

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```paste below
ansible 2.10.7
  config file = None
  configured module search path = ['/home/allanmo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by jborean93** [comment]
It's unfortunately a case where "global" variables is tricking us. `$AddressFamilies` is defined right at the beginning of the module https://github.com/ansible-collections/ansible.windows/blob/2a4950c438dbd6b6a1b9b2ea9d3db3dd1adac2d1/plugins/modules/win_dns_client.ps1#L12-L15. Because the `Get-RegistryNameServerInfo` is a child scope of where this is declared then `$AddressFamilies` will refer to this and thus should do the loop and check the values.

If you set `log_path: C:\path\to\log.txt` in your module options you should see some entries like `Current DNS setting for ...` and more detailed information about what `Test-DnsClientMatch` is doing to check if the settings need to be changed.

Can you share a specific example of when you are always seeing `changed=$true` in the module return?

**Comment by jborean93** [comment]
Closing due to no response. If there is a specific reproduce someone can share we can reopen and go from there.
