### ISSUE TITLE
win_certificate_store has no function to check for existing certificates or perform enrollments

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/ansible.windows#33]
_From @dubblies on Mar 17, 2020 15:23_

##### SUMMARY
no "get" capabilities - I cannot query for existing certificates or see their data

##### ISSUE TYPE
Please finish out the functionality here and if possible adopt Powershell for the Test-Path functionality at minimum if not full get-certificate functionality for enrollment as well

##### COMPONENT NAME
win_certificate_store

_Copied from original issue: ansible/ansible#68280_

**Comment by jborean93** [comment]
There is a new module that has been recently added and will be part of the [community.windows](https://github.com/ansible-collections/community.windows) collection release called [win_certificate_info](https://github.com/ansible-collections/community.windows/blob/master/plugins/modules/win_certificate_info.py).

As for certificate enrolment I have no idea what is involved in that but I would guess it would have to be a new module and not part of `win_certificate_store`. In any case that is a feature request and there are no plans on implementing this ourselves. You are more than welcome to implement this as a feature for `win_certificate_store` here if it makes sense or as a new module in `community.windows` but we've found there is little reason to keep feature requests like this open on GitHub because they just stagnate over the years.
