### ISSUE TITLE
Win_package Intermittent error

### ISSUE THREAD

**Issue by iasllanih** [ansible-collections/ansible.windows#350]
##### SUMMARY

Task module was adjusted after not working on new Ansible 5.6

We are coming from 2.9 and the task would hang, so I adjusted the install arguments. The package will now install, but on repeated runs, an intermittent issue appears, does not make sense as this would not happen in Ansible 2.9

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```yaml
- name: Executing Cylance Optics installer
  win_package:
    path: "{{ artifact_repository }}{{ cylance_optics_extension }}{{ cylance_optics_installer }}"
    product_id: "{{ cylance_optics_product_id }}"
    arguments:
    - /quiet
    state: present
```

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.8.5 (default, Aug 27 2020, 18:15:13) [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)]
  jinja version = 3.1.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
bash-4.2# ansible-galaxy collection list community.windows

# /opt/ansible/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.9.0
```

##### CONFIGURATION

```paste below
bash-4.2# ansible-config dump --only-changed
bash-4.2#

```

##### OS / ENVIRONMENT

Windows Server 2019 Standard Base

##### STEPS TO REPRODUCE

Run the task module, initial run reports a change. Validate on OS, looks good. 

On rerun, get the error. 
We are grabbing the .exe from artifactory, I have also tried to download and install locally, same error.

```yaml
Using molecule to test, so running molecule converge.
```

##### EXPECTED RESULTS

Just get the OK like we did in 2.9, and from some other packages. Show idempotence

**IMPORTANT: this isnt the only package where this happens. It has happened on Git installs and sysinternals as well.**

##### ACTUAL RESULTS

Failure and run stops. 

```paste below
[WARNING]: Module invocation had junk after the JSON data:  An error has
occurred that was not properly handled. Additional information is shown below.
The Windows PowerShell process will exit.
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 1485
fatal: [molecule--windows-base-role-srv19-01]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Exception calling \"ExitJson\" with \"0\" argument(s): \"Access to the path 'CylanceOPTICSSetup.exe' is denied.\""}

    PLAY RECAP *********************************************************************
    molecule--windows-base-role-srv19-01 : ok=39   changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

```

**Comment by jborean93** [comment]
> We are coming from 2.9 and the task would hang, so I adjusted the install arguments. The package will now install, but on repeated runs, an intermittent issue appears, does not make sense as this would not happen in Ansible 2.9

Are you able to confirm if `win_package` failed all the time on 2.9 or it only started to fail when you upgraded?

Can you also run with `-vvv` so we can see the exception that occurred? One thing to note is that `win_package` went through a bit rewrite once it was moved to the collection so things like downloading changed a lot.

**Comment by iasllanih** [comment]
Yes I can confirm on 2.9 we have never seen that error. (Been on 2.9 since May 2020). Once we figure out the best combo of arguments, the task worked as expected and was idempotent on reruns.

Sorry, due to it being intermittent, took some time to reproduce, but here is the error with increased verbosity:
FYI the user is a local admin on the VM... so permissions shouldnt really play an issue. It works in 2.9
`
    TASK [hs_role_base_windows : Executing Cylance Optics installer] ***************
    task path: /opt/ansible/hs_role_base_windows/tasks/cylance.yml:15
    redirecting (type: modules) ansible.builtin.win_package to ansible.windows.win_package
    Using module file /opt/ansible/lib/python3.8/site-packages/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
    Pipelining is enabled.
    <PRIVATE_IP> ESTABLISH WINRM CONNECTION FOR USER: molecule on PORT 5986 TO PRIVATE_IP
    EXEC (via pipeline wrapper)
[WARNING]: Module invocation had junk after the JSON data:  An error has
occurred that was not properly handled. Additional information is shown below.
The Windows PowerShell process will exit.

    PLAY RECAP *********************************************************************
The full traceback is:
Exception calling "ExitJson" with "0" argument(s): "Access to the path 'CylanceOPTICSSetup.exe' is denied."
At line:1485 char:1
+ $module.ExitJson()
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccessException

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 1485
fatal: [molecule--windows-base-role-srv19-01]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception calling \"ExitJson\" with \"0\" argument(s): \"Access to the path 'CylanceOPTICSSetup.exe' is denied.\""
}
    molecule--windows-base-role-srv19-01 : ok=8    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

**Comment by jborean93** [comment]
Thanks for the information, from what you've shared it looks like the problem is happening on the `Tmpdir` cleanup phase of a module that is called with `ExitJson()`. The `Tmpdir` here is used by `win_package` to store any temporary files downloaded or copied when it ran. This happens if `path` is a URL or a UNC path. This is just me guessing but what I believe is happening is that when the module exits, it goes to remove the `Tmpdir` which includes the installer you have but something is still holding a handle on the exe. This could potentially be something in the code, or it could be anything the installer itself has spawned. Unfortunately figuring what exactly this is is going to be difficult.

I'll have to try and see if I can also get this installer and manually test it on my host. You did mention you downloaded that downloading it locally and installing ti from there also failed. Can you confirm that is the case and that the error you get back is also the same? I'm not sure how it would also fail with the same error here as no copying or downloading should be occurring in the `Tmpdir`.

As for why 2.9 is unaffected, it did not use the module `Tmpdir` mechanism but rather some builtin mechanism.

**Comment by iasllanih** [comment]
So I've spent some time today testing to get the error from installing a package downloaded locally and I could not replicate the error.

Though I thought this was the case prior, I suppose that would support your theory. Any idea how we can proceed?

**Comment by jborean93** [comment]
> Though I thought this was the case prior, I suppose that would support your theory. Any idea how we can proceed?

Thanks for sharing that information it definitely helps and gives more support to my theory. The next step is for me to try and replicate the problem. I've found a copy of `CylanceOPTICSSetup.exe` that I can try and replicate with and see what might be happening and will get back to you once I've gotten a bit more information.

**Comment by jborean93** [comment]
So I've spent some time today trying to replicate this problem but I cannot. It was hard to find a copy of the installer as it doesn't seem to be available anywhere publicly. I was able to find a copy from a GitHub repo that held a DSC role to install the product and came up with the following playbook to install it.

```yaml
- hosts: adhoc
  gather_facts: no
  tasks:
  - ansible.windows.win_package:
      path: https://raw.githubusercontent.com/Maliek/CylanceProtect-Windows-Deployment-Azure-ARM/master/CylanceProtect_x64.msi
      state: present
      arguments: PIDKEY=XXXXXXXXXXXXXXXXXXXXXXXXX

  - ansible.windows.win_package:
      path: https://raw.githubusercontent.com/Maliek/CylanceProtect-Windows-Deployment-Azure-ARM/master/CylanceOPTICSSetup.exe
      product_id: '{6FECE3E5-CA63-4A30-A29D-3600F2057F41}'
      state: present
      arguments: /quiet
```

I've run this playbook 10+ times on both the `psrp` and `winrm` connection plugin and haven't encountered the problem you see. In all cases the temp folder is deleted once the installer has finished. The only issue I had was that Cylance Protect needed to be installed first for the silently installer for Cylance OPTICS to work.

Unfortunately there's not much else I can do in this situation, if the installer is somehow persisting beyond the module invocation and stopping something from deleting the temp dir created then the only real recourse is to avoid the temp file in the first place. This is done by downloading the installer beforehand using `win_get_url` as a separate task.

The only thing I can do in this situation is to fix up the unhandled exception problem by more gracefully handling the tempdir deletion problem. While this doesn't fix the root cause of the problem it will at least give a better error message, or mabye a warning, in the response.

**Comment by iasllanih** [comment]
Ideally, we would like to continue with installs with URL paths, especially since it is working in 2.9. 
Question, why would Cylance Optics even be in the tmp dir if it is already installed?
On completed runs, ansible recognizes that there is no change (idempotency obviously), so why would it try to place the installer in this dir?

Thank you for giving it a shot, and you are correct, Cylance Protect is required prior to Optics.

**Comment by ademestihas** [comment]
We have this same problem in ansible 2.14.1 installing c# redistributable packages across multiple servers where 1 server will fail each time and its different every day.  We're installing them across probably 20 servers/day and 1 will fail in each stage each day. with access denied to the 

The full traceback is:
   at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveFileSystemItem(FileSystemInfo fileSystemInfo, Boolean force)
fatal: [ATO-SPWEB-01.daily.local]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Access to the path 'C:\\Users\\Administrator.daily\\AppData\\Local\\Temp\\ansible-moduletmp-133240994497384829-459045827\\vcredist_x64.exe' is denied."
}

**Comment by jborean93** [comment]
The PR https://github.com/ansible/ansible/pull/80293#pullrequestreview-1355856387 should help alleviate this problem. Unfortunately it won’t solve it completely but it works in more situations and instead of erroring it is now going to be a warning.
