### ISSUE TITLE
How to configure Ansible to set MaxProtocol = TLSv1.2 for ssl connections to Windows endpoints

### ISSUE THREAD

**Issue by cccscdev** [ansible-collections/ansible.windows#402]
This is a follow-on from the discussion in https://github.com/ansible-collections/ansible.windows/issues/333

A workaround proposed there was to modify the Windows registry to disable TLS 1.3.  However, we don't wish to do this, since it is a system-wide change.

Instead I am hoping that a configuration change can be made on the Ansible host side.  From my research (of openssl at least) it appears that the openssl.cnf can be modified to set MaxProtocol = TLSv1.2, which should mean that a maximum of TLS 1.2 should be offered by the client (the Ansible host) to the Windows Server during TLS handshaking.

I have attempted to make the changes to my openssl.cnf file, but this doesn't appear to have made any difference.  A Wireshark capture shows the Ansible host is still offering TLS 1.3 to the Windows server.

This leads me to wonder if Ansible (pywinrm) is really sourcing the ssl config from this file?  If this actually uses the Python ssl module, how can I apply the same configuration change to there?

**Comment by jborean93** [comment]
Continuing on https://github.com/diyan/pywinrm/issues/353

**Comment by agibson2** [comment]
I saw something mentioned about TLS 1.3 fixed in the latest round of Microsoft updates.  Not sure if it is related to the 1.3 issue you mention though.

"Addresses an issue when Ssl negotiation can hang indefinitely when client certificates are used when TLS 1.3 is negotiated. Before the change renegotiation (PostHandshakeAuthentiction) would fail and SslStream or HttpWebRequest would observe timeout. Possible workaround is disabling TLS 1.3 either via Switch.System.Net.DontEnableTls13 AppContext or via OS registry."

https://devblogs.microsoft.com/dotnet/dotnet-framework-august-2022-security-and-quality-rollup-updates/

**Comment by jborean93** [comment]
It's worth a shot to try out but I would be surprised if it fixed it. The WinRM service uses the HTTP.sys stack which sits outside of the .NET Framework but who know maybe it fixed 2 things at once.
