### ISSUE TITLE
Add missing documentation for some plugins

### ISSUE THREAD

**Issue by samccann** [ansible-collections/ansible.windows#421]
##### SUMMARY

A small set of plugins are not showing any documentation on docs.ansible.com. Details in followon comment

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
2.14
```

**Comment by samccann** [comment]
These modules are saying there is no documentation:

- [async_status module](https://docs.ansible.com/ansible/devel/collections/ansible/windows/async_status_module.html#ansible-collections-ansible-windows-async-status-module) –

- [setup module](https://docs.ansible.com/ansible/devel/collections/ansible/windows/setup_module.html#ansible-collections-ansible-windows-setup-module) –

- [slurp module](https://docs.ansible.com/ansible/devel/collections/ansible/windows/slurp_module.html#ansible-collections-ansible-windows-slurp-module) –

This filter plugin shows a similar problem - 
[quote filter](https://docs.ansible.com/ansible/devel/collections/ansible/windows/quote_filter.html#ansible-collections-ansible-windows-quote-filter) –

NOTE: core-2.14 just added support for filter plugins as the sidecar docs feature. This allows you to document the filter in an adjacent yaml file. See  https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/b64decode.yml for an example.

Related to https://github.com/ansible-community/community-team/issues/65

**Comment by jborean93** [comment]
These were documented as sidecar in https://github.com/ansible-collections/ansible.windows/pull/416. I've yet to push a release but the next time I do that should enable the docs to appear.

Historically we couldn't document it as a `.py` doc stub due to conflicts with the builtin `setup.py`, `async_status.py`, `slurp.py` modules in Ansible itself but sidecar made the above possible.

Closing as there's nothing left to do in this repo for this task.
