### ISSUE TITLE
win_tempfile.ps1 DOS 8.3 issues

### ISSUE THREAD

**Issue by PKehnel** [ansible-collections/ansible.windows#449]
##### SUMMARY
Creating a tmp file with the win_tempfile module is not working as expected. I assume it related to the DOS 8.3 part of the script. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_tempfile.ps1

##### ANSIBLE VERSION
```
ansible [core 2.13.0]
```

##### OS / ENVIRONMENT
Windows

##### STEPS TO REPRODUCE
Create a file with win_tempfile on a server with a temp profile

##### EXPECTED RESULTS
Create a file.

##### ACTUAL RESULTS

The file is not created in the return path of the module. My assumption is that the root cause is the `~` in the args.
Maybe the check from the script: `# Makes sure we get the full absolute path of the created temp file and not a relative or DOS 8.3 dir` is not working here? 

```
{
    "state": "file",
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "path": "C:\\Users\\TEMPWW~1.077\\AppData\\Local\\Temp",
            "state": "file",
            "prefix": "windows_port_facts",
            "suffix": ".ps1"
        }
    },
    "path": "C:\\Users\\TEMP.WW.077\\AppData\\Local\\Temp\\windows_port_factsvdoma1bw.fy3.ps1",
    "changed": true
}
```

**Comment by jborean93** [comment]
The problem here is the fact your user profile is using a TEMP profile path. Once the user has been logged off the temp profile created by this module is being deleted by windows. While this may or may not be the problem you have this does go into more details on temporary profiles by Windows https://answers.microsoft.com/en-us/windows/forum/all/windows-temporary-user-profile-temp-issue/5fbefc7c-0b82-4395-bfda-6d7e2ebeacc6.

Unfortunately there's nothing we can do here, the module is creating the temp file properly, it's just being deleted by Windows once the task is complete.
