### ISSUE TITLE
win_service always fail on service start retry on multiple OS versions .

### ISSUE THREAD

**Issue by neonmb** [ansible-collections/ansible.windows#450]
##### SUMMARY
Seems that the retry option is not compatible with win_service module. When using retry on win_service service start,  second attempt is always finish with the same error no matter WIN OS version. 
```
FAILED - RETRYING: If some services are down try to restart. (12 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: WinRMTransportError: Bad HTTP response returned from the server. Code: 400, Content: ''
fatal: [XXXX.hostname.com]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_service with parameter started. 

##### ANSIBLE VERSION
Ansible 2.9.27

##### COLLECTION VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
multiple Windows versions impacted. 
We have almost all WIN version in our inventory and for all versions its the same error. Recently running on:
"distribution = Microsoft Windows Server 2016 Standard", 
        "distribution_version = 10.0.14393.0", 

##### STEPS TO REPRODUCE
```
- name: If some services are down try to restart. 
  ignore_errors: true
  win_service:
    name: "{{ item }}"
    state: started
  with_items: "{{ service_info.stdout_lines }}"
  register: service_restart
  changed_when: service_restart.exists|bool == false
  retries: 12
  delay: 600
  until: service_restart is not failed
service_info.stdout_lines:
service1
service2
service3
```
##### EXPECTED RESULTS
I expect to retry the service start 
##### ACTUAL RESULTS
    "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 113, in run\n    item_results = self._run_loop(items)\n  File \"/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 367, in _run_loop\n    res = self._execute(variables=task_vars)\n  File \"/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py\", line 665, in _execute\n    result = self._handler.run(task_vars=variables)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py\", line 47, in run\n    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 933, in _execute_module\n    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py\", line 1085, in _low_level_execute_command\n    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/connection/psrp.py\", line 452, in exec_command\n    rc, stdout, stderr = self._exec_psrp_script(script, in_data)\n  File \"/usr/lib/python2.7/site-packages/ansible/plugins/connection/psrp.py\", line 874, in _exec_psrp_script\n    ps.invoke(input=input_data)\n  File \"/var/lib/awx/venv/ansible_ibm/lib/python2.7/site-packages/pypsrp/powershell.py\", line 1101, in invoke\n    redirect_shell_error_to_out, remote_stream_options)\n  File \"/var/lib/awx/venv/ansible_ibm/lib/python2.7/site-packages/pypsrp/powershell.py\", line 1039, in begin_invoke\n    self._invoke(create_pipeline)\n  File \"/var/lib/awx/venv/ansible_ibm/lib/python2.7/site-packages/pypsrp/powershell.py\", line 1294, in _invoke\n    command_id=self.id)\n  File \"/var/lib/awx/venv/ansible_ibm/lib/python2.7/site-packages/pypsrp/shell.py\", line 143, in command\n    selector_set=self._selector_set)\n  File \"/var/lib/awx/venv/ansible_ibm/lib/python2.7/site-packages/pypsrp/wsman.py\", line 258, in command\n    option_set, selector_set, timeout)\n  File \"/var/lib/awx/venv/ansible_ibm/lib/python2.7/site-packages/pypsrp/wsman.py\", line 398, in invoke\n    raise err\nWinRMTransportError: Bad HTTP response returned from the server. Code: 400, Content: ''\n",

**Comment by jborean93** [comment]
The problem here is `retires` only applies to task failures and not connection failures. While they can technically be argued as the same it's a historical thing with Ansible and not something that is controlled in this collection. Ultimately starting a service is bringing down the WinRM connection causing it to mark the host as unreachable.

You can use the `ignore_unreachable` option to ignore unreachable hosts which is documented under https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_error_handling.html#ignoring-unreachable-host-errors. Unfortunately it's not easy to combine ignore_unreachable with task retries so I don't really have any suggestions for you there. Ultimately anything that touches the connection that Ansible is using is going to be difficult to handle. It's why we have a specific plugin for rebooting a host and even then it's very complex to deal with connections going down. You should try and figure out what service is bringing down the service and find some other way to start it, maybe set as automatic startup and reboot the host.
