### ISSUE TITLE
How can win_acl be used to obtain the status of a file?

### ISSUE THREAD

**Issue by leanovv** [ansible-collections/ansible.windows#483]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)
I want to obtain the ACL list of a file path through win_acl and then delete all users except for the three users: System, Administrators, and Service. However, it seems to be unsuccessful. So, I tried to get the JSON format using PowerShell commands and then import variables to execute. 
    - name: Get current ACL settings on the D
      ansible.windows.win_shell: |
        (Get-Acl -Path d:\).Access | Where-Object {$_.IdentityReference.Value -notmatch "Administrators|SYSTEM|SERVICE"}| Select-Object FileSystemRights, AccessControlType, IdentityReference | ForEach-Object {
            $identityReference = $_.IdentityReference -replace '\\', '\'
            $jsonObj = @{
                FileSystemRights   = $_.FileSystemRights.ToString()
                AccessControlType  = $_.AccessControlType.ToString()
                IdentityReference  = $identityReference
            }
            $jsonObj | ConvertTo-Json 
        }
      register: current_acl_settings   

    - name:
      debug:    
        var: current_acl_settings.stdout_lines

During the process of setting variables, special characters were escaped, which has troubled me for a long time.

        ok: [43.248.136.219] => {
    "acl_settings": [
        "{",
        "    \"AccessControlType\":  \"Allow\",",
        "    \"IdentityReference\":  \"CREATOR OWNER\",",
        "    \"FileSystemRights\":  \"FullControl\"",
        "}",
        "{",
        "    \"AccessControlType\":  \"Allow\",",
        "    \"IdentityReference\":  \"BUILTIN\\\\Users\",",
        "    \"FileSystemRights\":  \"AppendData\"",
        "}",
        "{",
        "    \"AccessControlType\":  \"Allow\",",
        "    \"IdentityReference\":  \"BUILTIN\\\\Users\",",
        "    \"FileSystemRights\":  \"CreateFiles\"",
        "}"
    ]
}

**Comment by jborean93** [comment]
You should have a look at using `[ansible.windows.win_powershell](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_powershell_module.html) which outputs pwsh objects as lists and dictionaries you can manage in Ansible without the JSON conversion.. If you still wanted to continue using `win_shell` then you need to do `current_acl_settings.stdout | from_json` to get the list of dictionary objects you are expecting.


This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on [irc.libera.chat](https://libera.chat/)
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If don't you think this particular issue is resolved, you should still stop by there first, we'd appreciate it.
This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
