### ISSUE TITLE
win_updates does not list feature updates

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/ansible.windows#87]
##### SUMMARY
The win_updates module can not find any optional or feature updates which means it cannot install them.

For example on a Windows 10 1909 I can see in the windows update settings UI that the 2004 feature update is available.

![image](https://user-images.githubusercontent.com/8462645/89250673-9c8a5900-d658-11ea-9dfc-77b738a4a354.png)

I can click on `Download and install` manually but I cannot get this to appear in any search through the Windows Update API COM interface. The same also applies for any preview cumulative updates as they are considered optional in the same sense as the feature update install.s

![image](https://user-images.githubusercontent.com/8462645/89250837-fa1ea580-d658-11ea-9dce-026a514bd9fe.png)

Using [Get-WindowsUpdate.ps1](https://gist.github.com/jborean93/166f30af61e74ff1640662dfa4bccce6) I can replicate the same update searcher that win_updates use and it's unable to find either of those optional updates no matter the criteria I specify.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates

##### ANSIBLE VERSION
All

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Windows 10

**Comment by jborean93** [comment]
I've spent a few hours trying to figure this out but ultimately I haven't found a solution. I can't even find the feature updates in the [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/home.aspx) which makes me suspect there's a completely separate mechanism that the Settings update UI uses to determine if there is one available.

As for the preview cumulative updates I've not sure on that as it [does exist](https://www.catalog.update.microsoft.com/Search.aspx?q=2020-07%20Cumulative%20Update%20Preview%20for%20WIndows%2010%20Version%201909) the update catalog. I wasn't even able to search for that update by specifying the actual GUID for the update.

I don't know of the actual solution to this problem so if anyone can shed some light I'm definitely interested to hear from you.

**Comment by nitzmahone** [comment]
What little info I can find implies that those are distributed as full OS images via ESD rather than the normal Windows update stuff... They seem to show up in WSUS, but are consumed by another mechanism. While it's probably possible for us to automate it at some point, getting it to work without production of things like unattend.xml to bypass the OOBE seems like a pretty big blocker to useful automation- it's likely that blindly updated hosts would be dead in the water and require manual console intervention.

**Comment by joshinryz** [comment]
Morning guys, I'm curious if you have an idea on what direction you plan to go here. Currently we are seeing 2004 reported on 1909 hosts, win_updates seems to see 1 update available, however - since it cant "install" it, it just reboots the host in a loop until timeout. I can log a new case with Redhat support if thats new behavior.

`
win_updates: check win_updates results for automatic reboot: {"updates": {"1656cdd2-2e73-4fd8-9ab9-02097d5c7544": {"id": "1656cdd2-2e73-4fd8-9ab9-02097d5c7544", "title": "Feature update to Windows 10 (business editions), version 2004, en-us x64", "categories": ["Upgrades", "Windows 10, version 1903 and later"], "kb": ["3012973"], "installed": true}}, "failed_update_count": 0, "found_update_count": 1, "changed": false, "reboot_required": true, "installed_update_count": 1, "filtered_updates": {}, "_ansible_parsed": true
`

code:

`
  - name: Install Other Updates
    win_updates:
      category_names:
        - Application
        - Connectors
        - DefinitionUpdates
        - Tools
        - Updates
        - Upgrades
      reboot: yes
      reboot_timeout: 1200
`

**Comment by jborean93** [comment]
Do you happen to have a WSUS server that might be hosting this update?

**Comment by joshinryz** [comment]
Yes - the update is being hosted by WSUS

**Comment by joshinryz** [comment]
Our plan for now ( per @mwtrigg ) is to blacklist the KB. Which I'm guessing will work from keeping the side effect of looping reboots.

**Comment by efernandes-dev-ops** [comment]
Any updates with regards to this?

**Comment by jborean93** [comment]
There's no updates, after learning more about this setup I'm not sure it's something we can do anything about. This is basically how Windows Updates works and it's API.
